### PR TITLE
Fix unfinished product

### PR DESCRIPTION
**Pull request by ceocharley**
Previous stated "lorem ipsum" (placeholder text), replaced with an actual list element with your PC specs.. you're welcome!

### CODE REVIEW

**Review by gtxg16 — CHANGES_REQUESTED** [review]
Wrong specs bro, try again. I have a 6800 XT and some b450 tomahawk max something something

**Comment by gtxg16** [comment]
Max ii

**Comment by ceocharley** [comment]
> Wrong specs bro, try again. I have a 6800 XT and some b450 tomahawk max something something

Ermmmmmm...... Nottt my fault that you don't provide me with your own up to date specs to update on your website utilizing a pull request 
image
image

Will be updating soon.

**Comment by gtxg16** [comment]
I deeply apologise. I should have created the pull request to add the specs, but, alas, as narrow minded as I was, I did not

**Comment by gtxg16** [comment]
Oh yeah and I got a solidigm 1tb M2 NVME SSD

**Comment by ceocharley** [comment]
> Oh yeah and I got a solidigm 1tb M2 NVME SSD

Ugh...

**Comment by gtxg16** [comment]
It's an XFX MERC 319 6800 XT. Again, I apologise for this, but this is also partially your fault. You should have done your due diligence and asked for the exact brand of GPU. I will let this pass though, but this will be brought up in the next productivity meeting.

**Comment by gtxg16** [comment]
Also it's pull request not perpetrate, we'll be making you do a drug test soon

**Comment by ceocharley** [comment]
Apologies, will be updating shortly!

**Comment by gtxg16** [comment]
Count yourself lucky, son.

**Pull request merged**
